baseURL = "http://localhost:1313"
languageCode = "en"
DefaultContentLanguage = "en"
#title = "Blog of L.E. Torres"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
    title = "L.E. Torres"
    author = "L.E. Torres"
    #copyright = "2021-2022"
    description = "Blog of author Luis Enrique Torres"
    profilePicture = "images/profile.png"
    keywords=""
    favicon="favicons/"
    dateFormat = "Mon, Jan 2, 2006"
    mainSections = ["post"]
    images=["images/site-feature-image.png"]

    ## Social links
    # use 'fab' when brand icons, use 'fas' when standard solid icons.
    [[socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://de.linkedin.com/"

    [[socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/lxndrblz/anatole/"

    [[socialIcons]]
    icon = "fab fa-instagram"
    title = "instagram"
    url = "https://www.instagram.com/"

    [[socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:mail@example.com"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

[Languages]
    [Languages.en]
        title = "My blog"
        weight = 1
        LanguageName = "EN"
        contentDir = "content/english"


#[Permalinks]
#    post = "/:filename/"
